/**
 * DXCC Entity Code Lookup Table
 * Source: ADIF 3.1.6 Specification (https://adif.org/316/ADIF_316.htm)
 *
 * Used as fallback when ADIF files do not contain COUNTRY or CONT fields.
 * Includes current and deleted entities with continent codes.
 *
 * Format: { code: [name, continent, isDeleted, wikipediaSlug] }
 * wikipediaSlug: null = auto-generate from name, string = exact Wikipedia article title
 * Auto-generation replaces spaces with underscores and uses the name as-is.
 * Wikipedia URL: https://en.wikipedia.org/wiki/${slug}
 */
const DXCC_ENTITIES = {
  1:   ['Canada', 'NA', false, null],
  2:   ['Abu Ail Is.', 'AS', true, 'Abu_Ali_Island'],
  3:   ['Afghanistan', 'AS', false, null],
  4:   ['Agalega & St. Brandon Is.', 'AF', false, 'Agalega'],
  5:   ['Aland Is.', 'EU', false, '%C3%85land_Islands'],
  6:   ['Alaska', 'NA', false, null],
  7:   ['Albania', 'EU', false, null],
  8:   ['Aldabra', 'AF', true, 'Aldabra'],
  9:   ['American Samoa', 'OC', false, null],
  10:  ['Amsterdam & St. Paul Is.', 'AF', false, 'Amsterdam_Island'],
  11:  ['Andaman & Nicobar Is.', 'AS', false, 'Andaman_and_Nicobar_Islands'],
  12:  ['Anguilla', 'NA', false, null],
  13:  ['Antarctica', 'AN', false, null],
  14:  ['Armenia', 'AS', false, null],
  15:  ['Asiatic Russia', 'AS', false, 'Asian_Russia'],
  16:  ['New Zealand Subantarctic Islands', 'OC', false, 'New_Zealand_Subantarctic_Islands'],
  17:  ['Aves I.', 'NA', false, 'Aves_Island'],
  18:  ['Azerbaijan', 'AS', false, null],
  19:  ['Bajo Nuevo', 'NA', true, 'Bajo_Nuevo_Bank'],
  20:  ['Baker & Howland Is.', 'OC', false, 'Baker_Island'],
  21:  ['Balearic Is.', 'EU', false, 'Balearic_Islands'],
  22:  ['Palau', 'OC', false, null],
  23:  ['Blenheim Reef', 'AF', true, 'Blenheim_Reef'],
  24:  ['Bouvet', 'AF', false, 'Bouvet_Island'],
  25:  ['British North Borneo', 'OC', true, 'North_Borneo'],
  26:  ['British Somaliland', 'AF', true, 'British_Somaliland'],
  27:  ['Belarus', 'EU', false, null],
  28:  ['Canal Zone', 'NA', true, 'Panama_Canal_Zone'],
  29:  ['Canary Is.', 'AF', false, 'Canary_Islands'],
  30:  ['Celebe & Molucca Is.', 'OC', true, 'Maluku_Islands'],
  31:  ['C. Kiribati (British Phoenix Is.)', 'OC', false, 'Phoenix_Islands'],
  32:  ['Ceuta & Melilla', 'AF', false, 'Ceuta_and_Melilla'],
  33:  ['Chagos Is.', 'AF', false, 'Chagos_Archipelago'],
  34:  ['Chatham Is.', 'OC', false, 'Chatham_Islands'],
  35:  ['Christmas I.', 'OC', false, 'Christmas_Island'],
  36:  ['Clipperton I.', 'NA', false, 'Clipperton_Island'],
  37:  ['Cocos I.', 'NA', false, 'Cocos_Island'],
  38:  ['Cocos (Keeling) Is.', 'OC', false, 'Cocos_(Keeling)_Islands'],
  39:  ['Comoros', 'AF', true, null],
  40:  ['Crete', 'EU', false, null],
  41:  ['Crozet I.', 'AF', false, 'Crozet_Islands'],
  42:  ['Damao, Diu', 'AS', true, 'Daman_and_Diu'],
  43:  ['Desecheo I.', 'NA', false, 'Desecheo_Island'],
  44:  ['Desroches', 'AF', true, 'Desroches_Island'],
  45:  ['Dodecanese', 'EU', false, 'Dodecanese'],
  46:  ['East Malaysia', 'OC', false, 'East_Malaysia'],
  47:  ['Easter I.', 'SA', false, 'Easter_Island'],
  48:  ['E. Kiribati (Line Is.)', 'OC', false, 'Line_Islands'],
  49:  ['Equatorial Guinea', 'AF', false, null],
  50:  ['Mexico', 'NA', false, null],
  51:  ['Eritrea', 'AF', false, null],
  52:  ['Estonia', 'EU', false, null],
  53:  ['Ethiopia', 'AF', false, null],
  54:  ['European Russia', 'EU', false, 'European_Russia'],
  55:  ['Farquhar', 'AF', true, 'Farquhar_Group'],
  56:  ['Fernando de Noronha', 'SA', false, 'Fernando_de_Noronha'],
  57:  ['French Equatorial Africa', 'AF', true, 'French_Equatorial_Africa'],
  58:  ['French Indo-China', 'AS', true, 'French_Indochina'],
  59:  ['French West Africa', 'AF', true, 'French_West_Africa'],
  60:  ['Bahamas', 'NA', false, 'The_Bahamas'],
  61:  ['Franz Josef Land', 'EU', false, 'Franz_Josef_Land'],
  62:  ['Barbados', 'NA', false, null],
  63:  ['French Guiana', 'SA', false, null],
  64:  ['Bermuda', 'NA', false, null],
  65:  ['British Virgin Is.', 'NA', false, 'British_Virgin_Islands'],
  66:  ['Belize', 'NA', false, null],
  67:  ['French India', 'AS', true, 'French_India'],
  68:  ['Kuwait/Saudi Arabia Neutral Zone', 'AS', true, 'Saudi_Arabian%E2%80%93Iraqi_neutral_zone'],
  69:  ['Cayman Is.', 'NA', false, 'Cayman_Islands'],
  70:  ['Cuba', 'NA', false, null],
  71:  ['Galapagos Is.', 'SA', false, 'Gal%C3%A1pagos_Islands'],
  72:  ['Dominican Republic', 'NA', false, null],
  74:  ['El Salvador', 'NA', false, null],
  75:  ['Georgia', 'AS', false, 'Georgia_(country)'],
  76:  ['Guatemala', 'NA', false, null],
  77:  ['Grenada', 'NA', false, null],
  78:  ['Haiti', 'NA', false, null],
  79:  ['Guadeloupe', 'NA', false, null],
  80:  ['Honduras', 'NA', false, null],
  81:  ['Germany', 'EU', true, null],
  82:  ['Jamaica', 'NA', false, null],
  84:  ['Martinique', 'NA', false, null],
  85:  ['Bonaire, Curacao', 'SA', true, 'ABC_islands_(Leeward_Antilles)'],
  86:  ['Nicaragua', 'NA', false, null],
  88:  ['Panama', 'NA', false, null],
  89:  ['Turks & Caicos Is.', 'NA', false, 'Turks_and_Caicos_Islands'],
  90:  ['Trinidad & Tobago', 'SA', false, 'Trinidad_and_Tobago'],
  91:  ['Aruba', 'SA', false, null],
  93:  ['Geyser Reef', 'AF', true, 'Geyser_Rock_(Indian_Ocean)'],
  94:  ['Antigua & Barbuda', 'NA', false, 'Antigua_and_Barbuda'],
  95:  ['Dominica', 'NA', false, null],
  96:  ['Montserrat', 'NA', false, null],
  97:  ['St. Lucia', 'NA', false, 'Saint_Lucia'],
  98:  ['St. Vincent', 'NA', false, 'Saint_Vincent_and_the_Grenadines'],
  99:  ['Glorioso Is.', 'AF', false, 'Glorioso_Islands'],
  100: ['Argentina', 'SA', false, null],
  101: ['Goa', 'AS', true, 'Goa'],
  102: ['Gold Coast, Togoland', 'AF', true, 'Gold_Coast_(British_colony)'],
  103: ['Guam', 'OC', false, null],
  104: ['Bolivia', 'SA', false, null],
  105: ['Guantanamo Bay', 'NA', false, 'Guantanamo_Bay_Naval_Base'],
  106: ['Guernsey', 'EU', false, null],
  107: ['Guinea', 'AF', false, null],
  108: ['Brazil', 'SA', false, null],
  109: ['Guinea-Bissau', 'AF', false, null],
  110: ['Hawaii', 'OC', false, null],
  111: ['Heard I.', 'AF', false, 'Heard_Island_and_McDonald_Islands'],
  112: ['Chile', 'SA', false, null],
  113: ['Ifni', 'AF', true, null],
  114: ['Isle of Man', 'EU', false, null],
  115: ['Italian Somaliland', 'AF', true, 'Italian_Somaliland'],
  116: ['Colombia', 'SA', false, null],
  117: ['ITU HQ', 'EU', false, 'International_Telecommunication_Union'],
  118: ['Jan Mayen', 'EU', false, null],
  119: ['Java', 'OC', true, null],
  120: ['Ecuador', 'SA', false, null],
  122: ['Jersey', 'EU', false, null],
  123: ['Johnston I.', 'OC', false, 'Johnston_Atoll'],
  124: ['Juan de Nova, Europa', 'AF', false, 'Juan_de_Nova_Island'],
  125: ['Juan Fernandez Is.', 'SA', false, 'Juan_Fern%C3%A1ndez_Islands'],
  126: ['Kaliningrad', 'EU', false, 'Kaliningrad_Oblast'],
  127: ['Kamaran Is.', 'AS', true, 'Kamaran'],
  128: ['Karelo-Finnish Republic', 'EU', true, 'Karelo-Finnish_Soviet_Socialist_Republic'],
  129: ['Guyana', 'SA', false, null],
  130: ['Kazakhstan', 'AS', false, null],
  131: ['Kerguelen Is.', 'AF', false, 'Kerguelen_Islands'],
  132: ['Paraguay', 'SA', false, null],
  133: ['Kermadec Is.', 'OC', false, 'Kermadec_Islands'],
  134: ['Kingman Reef', 'OC', true, null],
  135: ['Kyrgyzstan', 'AS', false, null],
  136: ['Peru', 'SA', false, null],
  137: ['Republic of Korea', 'AS', false, 'South_Korea'],
  138: ['Kure I.', 'OC', false, 'Kure_Atoll'],
  139: ['Kuria Muria I.', 'AS', true, 'Khuriy%C4%81_Muriy%C4%81_Islands'],
  140: ['Suriname', 'SA', false, null],
  141: ['Falkland Is.', 'SA', false, 'Falkland_Islands'],
  142: ['Lakshadweep Is.', 'AS', false, 'Lakshadweep'],
  143: ['Laos', 'AS', false, null],
  144: ['Uruguay', 'SA', false, null],
  145: ['Latvia', 'EU', false, null],
  146: ['Lithuania', 'EU', false, null],
  147: ['Lord Howe I.', 'OC', false, 'Lord_Howe_Island'],
  148: ['Venezuela', 'SA', false, null],
  149: ['Azores', 'EU', false, null],
  150: ['Australia', 'OC', false, null],
  151: ['Malyj Vysotskij I.', 'EU', true, 'Vysotsk'],
  152: ['Macao', 'AS', false, 'Macau'],
  153: ['Macquarie I.', 'OC', false, 'Macquarie_Island'],
  154: ['Yemen Arab Republic', 'AS', true, 'Yemen_Arab_Republic'],
  155: ['Malaya', 'AS', true, 'British_Malaya'],
  157: ['Nauru', 'OC', false, null],
  158: ['Vanuatu', 'OC', false, null],
  159: ['Maldives', 'AS', false, null],
  160: ['Tonga', 'OC', false, null],
  161: ['Malpelo I.', 'SA', false, 'Malpelo_Island'],
  162: ['New Caledonia', 'OC', false, null],
  163: ['Papua New Guinea', 'OC', false, null],
  164: ['Manchuria', 'AS', true, null],
  165: ['Mauritius', 'AF', false, null],
  166: ['Mariana Is.', 'OC', false, 'Northern_Mariana_Islands'],
  167: ['Market Reef', 'EU', false, 'Market_Reef'],
  168: ['Marshall Is.', 'OC', false, 'Marshall_Islands'],
  169: ['Mayotte', 'AF', false, null],
  170: ['New Zealand', 'OC', false, null],
  171: ['Mellish Reef', 'OC', false, 'Mellish_Reef'],
  172: ['Pitcairn I.', 'OC', false, 'Pitcairn_Islands'],
  173: ['Micronesia', 'OC', false, 'Federated_States_of_Micronesia'],
  174: ['Midway I.', 'OC', false, 'Midway_Atoll'],
  175: ['French Polynesia', 'OC', false, null],
  176: ['Fiji', 'OC', false, null],
  177: ['Minami Torishima', 'OC', false, 'Marcus_Island'],
  178: ['Minerva Reef', 'OC', true, null],
  179: ['Moldova', 'EU', false, null],
  180: ['Mount Athos', 'EU', false, 'Mount_Athos'],
  181: ['Mozambique', 'AF', false, null],
  182: ['Navassa I.', 'NA', false, 'Navassa_Island'],
  183: ['Netherlands Borneo', 'OC', true, 'Dutch_Borneo'],
  184: ['Netherlands New Guinea', 'OC', true, 'Netherlands_New_Guinea'],
  185: ['Solomon Is.', 'OC', false, 'Solomon_Islands'],
  186: ['Newfoundland, Labrador', 'NA', true, 'Newfoundland_and_Labrador'],
  187: ['Niger', 'AF', false, null],
  188: ['Niue', 'OC', false, null],
  189: ['Norfolk I.', 'OC', false, 'Norfolk_Island'],
  190: ['Samoa', 'OC', false, null],
  191: ['North Cook Is.', 'OC', false, 'Cook_Islands'],
  192: ['Ogasawara', 'AS', false, 'Ogasawara_Islands'],
  193: ['Okinawa (Ryukyu Is.)', 'AS', true, 'Ryukyu_Islands'],
  194: ['Okino Tori-Shima', 'AS', true, 'Okinotorishima'],
  195: ['Annobon I.', 'AF', false, 'Annob%C3%B3n'],
  196: ['Palestine', 'AS', true, 'State_of_Palestine'],
  197: ['Palmyra & Jarvis Is.', 'OC', false, 'Palmyra_Atoll'],
  198: ['Papua Territory', 'OC', true, 'Territory_of_Papua'],
  199: ['Peter 1 I.', 'AN', false, 'Peter_I_Island'],
  200: ['Portuguese Timor', 'OC', true, 'Portuguese_Timor'],
  201: ['Prince Edward & Marion Is.', 'AF', false, 'Prince_Edward_Islands'],
  202: ['Puerto Rico', 'NA', false, null],
  203: ['Andorra', 'EU', false, null],
  204: ['Revillagigedo', 'NA', false, 'Revillagigedo_Islands'],
  205: ['Ascension I.', 'AF', false, 'Ascension_Island'],
  206: ['Austria', 'EU', false, null],
  207: ['Rodrigues I.', 'AF', false, 'Rodrigues'],
  208: ['Ruanda-Urundi', 'AF', true, 'Ruanda-Urundi'],
  209: ['Belgium', 'EU', false, null],
  210: ['Saar', 'EU', true, 'Saar_Protectorate'],
  211: ['Sable I.', 'NA', false, 'Sable_Island'],
  212: ['Bulgaria', 'EU', false, null],
  213: ['Saint Martin', 'NA', false, 'Saint_Martin_(island)'],
  214: ['Corsica', 'EU', false, null],
  215: ['Cyprus', 'AS', false, null],
  216: ['San Andres & Providencia', 'NA', false, 'Archipelago_of_San_Andr%C3%A9s,_Providencia_and_Santa_Catalina'],
  217: ['San Felix & San Ambrosio', 'SA', false, 'Desventuradas_Islands'],
  218: ['Czechoslovakia', 'EU', true, null],
  219: ['Sao Tome & Principe', 'AF', false, 'S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe'],
  220: ['Sarawak', 'OC', true, null],
  221: ['Denmark', 'EU', false, null],
  222: ['Faroe Is.', 'EU', false, 'Faroe_Islands'],
  223: ['England', 'EU', false, null],
  224: ['Finland', 'EU', false, null],
  225: ['Sardinia', 'EU', false, null],
  226: ['Saudi Arabia/Iraq Neutral Zone', 'AS', true, 'Saudi_Arabian%E2%80%93Iraqi_neutral_zone'],
  227: ['France', 'EU', false, null],
  228: ['Serrana Bank & Roncador Cay', 'NA', true, 'Serranilla_Bank'],
  229: ['German Democratic Republic', 'EU', true, 'East_Germany'],
  230: ['Fed. Rep. of Germany', 'EU', false, 'Germany'],
  231: ['Sikkim', 'AS', true, null],
  232: ['Somalia', 'AF', false, null],
  233: ['Gibraltar', 'EU', false, null],
  234: ['South Cook Is.', 'OC', false, 'Cook_Islands'],
  235: ['South Georgia I.', 'SA', false, 'South_Georgia_Island'],
  236: ['Greece', 'EU', false, null],
  237: ['Greenland', 'NA', false, null],
  238: ['South Orkney Is.', 'SA', false, 'South_Orkney_Islands'],
  239: ['Hungary', 'EU', false, null],
  240: ['South Sandwich Is.', 'SA', false, 'South_Sandwich_Islands'],
  241: ['South Shetland Is.', 'AN', false, 'South_Shetland_Islands'],
  242: ['Iceland', 'EU', false, null],
  243: ["People's Dem. Rep. of Yemen", 'AS', true, 'South_Yemen'],
  244: ['Southern Sudan', 'AF', true, 'South_Sudan'],
  245: ['Ireland', 'EU', false, null],
  246: ['Sov. Mil. Order of Malta', 'EU', false, 'Sovereign_Military_Order_of_Malta'],
  247: ['Spratly Is.', 'AS', false, 'Spratly_Islands'],
  248: ['Italy', 'EU', false, null],
  249: ['St. Kitts & Nevis', 'NA', false, 'Saint_Kitts_and_Nevis'],
  250: ['St. Helena', 'AF', false, 'Saint_Helena'],
  251: ['Liechtenstein', 'EU', false, null],
  252: ['St. Paul I.', 'NA', false, 'Sable_Island'],
  253: ['St. Peter & St. Paul Rocks', 'SA', false, 'Saint_Peter_and_Saint_Paul_Archipelago'],
  254: ['Luxembourg', 'EU', false, null],
  255: ['St. Maarten, Saba, St. Eustatius', 'NA', true, 'Sint_Maarten'],
  256: ['Madeira Is.', 'AF', false, 'Madeira'],
  257: ['Malta', 'EU', false, null],
  258: ['Sumatra', 'OC', true, null],
  259: ['Svalbard', 'EU', false, null],
  260: ['Monaco', 'EU', false, null],
  261: ['Swan Is.', 'NA', true, 'Swan_Islands,_Honduras'],
  262: ['Tajikistan', 'AS', false, null],
  263: ['Netherlands', 'EU', false, null],
  264: ['Tangier', 'AF', true, 'International_Zone_of_Tangier'],
  265: ['Northern Ireland', 'EU', false, null],
  266: ['Norway', 'EU', false, null],
  267: ['Territory of New Guinea', 'OC', true, 'Territory_of_New_Guinea'],
  268: ['Tibet', 'AS', true, null],
  269: ['Poland', 'EU', false, null],
  270: ['Tokelau Is.', 'OC', false, 'Tokelau'],
  271: ['Trieste', 'EU', true, 'Free_Territory_of_Trieste'],
  272: ['Portugal', 'EU', false, null],
  273: ['Trindade & Martim Vaz Is.', 'SA', false, 'Trindade_and_Martim_Vaz'],
  274: ['Tristan da Cunha & Gough I.', 'AF', false, 'Tristan_da_Cunha'],
  275: ['Romania', 'EU', false, null],
  276: ['Tromelin I.', 'AF', false, 'Tromelin_Island'],
  277: ['St. Pierre & Miquelon', 'NA', false, 'Saint_Pierre_and_Miquelon'],
  278: ['San Marino', 'EU', false, null],
  279: ['Scotland', 'EU', false, null],
  280: ['Turkmenistan', 'AS', false, null],
  281: ['Spain', 'EU', false, null],
  282: ['Tuvalu', 'OC', false, null],
  283: ['UK Sov. Base Areas on Cyprus', 'AS', false, 'Akrotiri_and_Dhekelia'],
  284: ['Sweden', 'EU', false, null],
  285: ['Virgin Is.', 'NA', false, 'United_States_Virgin_Islands'],
  286: ['Uganda', 'AF', false, null],
  287: ['Switzerland', 'EU', false, null],
  288: ['Ukraine', 'EU', false, null],
  289: ['United Nations HQ', 'NA', false, 'United_Nations_Headquarters'],
  291: ['United States of America', 'NA', false, 'United_States'],
  292: ['Uzbekistan', 'AS', false, null],
  293: ['Viet Nam', 'AS', false, 'Vietnam'],
  294: ['Wales', 'EU', false, null],
  295: ['Vatican', 'EU', false, 'Vatican_City'],
  296: ['Serbia', 'EU', false, null],
  297: ['Wake I.', 'OC', false, 'Wake_Island'],
  298: ['Wallis & Futuna Is.', 'OC', false, 'Wallis_and_Futuna'],
  299: ['West Malaysia', 'AS', false, 'Peninsular_Malaysia'],
  301: ['W. Kiribati (Gilbert Is.)', 'OC', false, 'Gilbert_Islands'],
  302: ['Western Sahara', 'AF', false, null],
  303: ['Willis I.', 'OC', false, 'Willis_Island'],
  304: ['Bahrain', 'AS', false, null],
  305: ['Bangladesh', 'AS', false, null],
  306: ['Bhutan', 'AS', false, null],
  307: ['Zanzibar', 'AF', true, null],
  308: ['Costa Rica', 'NA', false, null],
  309: ['Myanmar', 'AS', false, null],
  312: ['Cambodia', 'AS', false, null],
  315: ['Sri Lanka', 'AS', false, null],
  318: ['China', 'AS', false, null],
  321: ['Hong Kong', 'AS', false, null],
  324: ['India', 'AS', false, null],
  327: ['Indonesia', 'OC', false, null],
  330: ['Iran', 'AS', false, null],
  333: ['Iraq', 'AS', false, null],
  336: ['Israel', 'AS', false, null],
  339: ['Japan', 'AS', false, null],
  342: ['Jordan', 'AS', false, null],
  344: ["Dem. People's Rep. of Korea", 'AS', false, 'North_Korea'],
  345: ['Brunei Darussalam', 'OC', false, 'Brunei'],
  348: ['Kuwait', 'AS', false, null],
  354: ['Lebanon', 'AS', false, null],
  363: ['Mongolia', 'AS', false, null],
  369: ['Nepal', 'AS', false, null],
  370: ['Oman', 'AS', false, null],
  372: ['Pakistan', 'AS', false, null],
  375: ['Philippines', 'OC', false, null],
  376: ['Qatar', 'AS', false, null],
  378: ['Saudi Arabia', 'AS', false, null],
  379: ['Seychelles', 'AF', false, null],
  381: ['Singapore', 'AS', false, null],
  382: ['Djibouti', 'AF', false, null],
  384: ['Syria', 'AS', false, null],
  386: ['Taiwan', 'AS', false, null],
  387: ['Thailand', 'AS', false, null],
  390: ['Turkey', 'EU', false, null],
  391: ['United Arab Emirates', 'AS', false, null],
  400: ['Algeria', 'AF', false, null],
  401: ['Angola', 'AF', false, null],
  402: ['Botswana', 'AF', false, null],
  404: ['Burundi', 'AF', false, null],
  406: ['Cameroon', 'AF', false, null],
  408: ['Central Africa', 'AF', false, 'Central_African_Republic'],
  409: ['Cape Verde', 'AF', false, null],
  410: ['Chad', 'AF', false, null],
  411: ['Comoros', 'AF', false, null],
  412: ['Republic of the Congo', 'AF', false, 'Republic_of_the_Congo'],
  414: ['Dem. Rep. of the Congo', 'AF', false, 'Democratic_Republic_of_the_Congo'],
  416: ['Benin', 'AF', false, null],
  420: ['Gabon', 'AF', false, null],
  422: ['The Gambia', 'AF', false, 'The_Gambia'],
  424: ['Ghana', 'AF', false, null],
  428: ["Cote d'Ivoire", 'AF', false, "C%C3%B4te_d'Ivoire"],
  430: ['Kenya', 'AF', false, null],
  432: ['Lesotho', 'AF', false, null],
  434: ['Liberia', 'AF', false, null],
  436: ['Libya', 'AF', false, null],
  438: ['Madagascar', 'AF', false, null],
  440: ['Malawi', 'AF', false, null],
  442: ['Mali', 'AF', false, null],
  444: ['Mauritania', 'AF', false, null],
  446: ['Morocco', 'AF', false, null],
  450: ['Nigeria', 'AF', false, null],
  452: ['Zimbabwe', 'AF', false, null],
  453: ['Reunion I.', 'AF', false, 'R%C3%A9union'],
  454: ['Rwanda', 'AF', false, null],
  456: ['Senegal', 'AF', false, null],
  458: ['Sierra Leone', 'AF', false, null],
  460: ['Rotuma I.', 'OC', false, 'Rotuma'],
  462: ['Republic of South Africa', 'AF', false, 'South_Africa'],
  464: ['Namibia', 'AF', false, null],
  466: ['Sudan', 'AF', false, null],
  468: ['Kingdom of Eswatini', 'AF', false, 'Eswatini'],
  470: ['Tanzania', 'AF', false, null],
  474: ['Tunisia', 'AF', false, null],
  478: ['Egypt', 'AF', false, null],
  480: ['Burkina Faso', 'AF', false, null],
  482: ['Zambia', 'AF', false, null],
  483: ['Togo', 'AF', false, null],
  488: ['Walvis Bay', 'AF', true, 'Walvis_Bay'],
  489: ['Conway Reef', 'OC', false, 'Conway_Reef'],
  490: ['Banaba I. (Ocean I.)', 'OC', false, 'Banaba_Island'],
  492: ['Yemen', 'AS', false, null],
  493: ['Penguin Is.', 'AF', true, 'Penguin_Islands_(Namibia)'],
  497: ['Croatia', 'EU', false, null],
  499: ['Slovenia', 'EU', false, null],
  501: ['Bosnia-Herzegovina', 'EU', false, 'Bosnia_and_Herzegovina'],
  502: ['North Macedonia', 'EU', false, null],
  503: ['Czech Republic', 'EU', false, null],
  504: ['Slovak Republic', 'EU', false, 'Slovakia'],
  505: ['Pratas I.', 'AS', false, 'Pratas_Island'],
  506: ['Scarborough Reef', 'AS', false, 'Scarborough_Shoal'],
  507: ['Temotu Province', 'OC', false, 'Temotu_Province'],
  508: ['Austral I.', 'OC', false, 'Austral_Islands'],
  509: ['Marquesas Is.', 'OC', false, 'Marquesas_Islands'],
  510: ['Palestine', 'AS', false, 'State_of_Palestine'],
  511: ['Timor-Leste', 'OC', false, null],
  512: ['Chesterfield Is.', 'OC', false, 'Chesterfield_Islands'],
  513: ['Ducie I.', 'OC', false, 'Ducie_Island'],
  514: ['Montenegro', 'EU', false, null],
  515: ['Swains I.', 'OC', false, 'Swains_Island'],
  516: ['Saint Barthelemy', 'NA', false, 'Saint_Barth%C3%A9lemy'],
  517: ['Curacao', 'SA', false, 'Cura%C3%A7ao'],
  518: ['Sint Maarten', 'NA', false, null],
  519: ['Saba & St. Eustatius', 'NA', false, 'Saba'],
  520: ['Bonaire', 'SA', false, null],
  521: ['South Sudan', 'AF', false, null],
  522: ['Republic of Kosovo', 'EU', false, 'Kosovo'],
}

/**
 * Get Wikipedia URL for a DXCC entity
 * @param {string|number} code - DXCC entity code
 * @returns {string} Full Wikipedia URL
 */
export function getWikipediaUrl(code) {
  const entry = DXCC_ENTITIES[Number(code)]
  if (!entry) return null
  const slug = entry[3]
  if (slug === null) {
    // Auto-generate from name: replace spaces with underscores
    const autoSlug = entry[0].replace(/ /g, '_')
    return `https://en.wikipedia.org/wiki/${autoSlug}`
  }
  return `https://en.wikipedia.org/wiki/${slug}`
}

/**
 * Look up DXCC entity by code
 * @param {string|number} code - DXCC entity code
 * @returns {{ name: string, cont: string, deleted: boolean } | null}
 */
export function lookupDXCC(code) {
  const entry = DXCC_ENTITIES[Number(code)]
  if (!entry) return null
  return { name: entry[0], cont: entry[1], deleted: entry[2] }
}

/**
 * Get all active (non-deleted) DXCC entities
 * @returns {Array<{ id: string, name: string, cont: string }>}
 */
export function getAllActiveDXCC() {
  return Object.entries(DXCC_ENTITIES)
    .filter(([_, entry]) => !entry[2]) // exclude deleted
    .map(([id, entry]) => ({ id, name: entry[0], cont: entry[1] }))
}

export default DXCC_ENTITIES
