/**
 * DXCC Entity Code Lookup Table
 * Source: ADIF 3.1.6 Specification (https://adif.org/316/ADIF_316.htm)
 *
 * Used as fallback when ADIF files do not contain COUNTRY or CONT fields.
 * Includes current and deleted entities with continent codes.
 *
 * Format: { code: [name, continent, isDeleted] }
 */
const DXCC_ENTITIES = {
  1: ['Canada', 'NA', false],
  2: ['Abu Ail Is.', 'AS', true],
  3: ['Afghanistan', 'AS', false],
  4: ['Agalega & St. Brandon Is.', 'AF', false],
  5: ['Aland Is.', 'EU', false],
  6: ['Alaska', 'NA', false],
  7: ['Albania', 'EU', false],
  8: ['Aldabra', 'AF', true],
  9: ['American Samoa', 'OC', false],
  10: ['Amsterdam & St. Paul Is.', 'AF', false],
  11: ['Andaman & Nicobar Is.', 'AS', false],
  12: ['Anguilla', 'NA', false],
  13: ['Antarctica', 'AN', false],
  14: ['Armenia', 'AS', false],
  15: ['Asiatic Russia', 'AS', false],
  16: ['New Zealand Subantarctic Islands', 'OC', false],
  17: ['Aves I.', 'NA', false],
  18: ['Azerbaijan', 'AS', false],
  19: ['Bajo Nuevo', 'NA', true],
  20: ['Baker & Howland Is.', 'OC', false],
  21: ['Balearic Is.', 'EU', false],
  22: ['Palau', 'OC', false],
  23: ['Blenheim Reef', 'AF', true],
  24: ['Bouvet', 'AF', false],
  25: ['British North Borneo', 'OC', true],
  26: ['British Somaliland', 'AF', true],
  27: ['Belarus', 'EU', false],
  28: ['Canal Zone', 'NA', true],
  29: ['Canary Is.', 'AF', false],
  30: ['Celebe & Molucca Is.', 'OC', true],
  31: ['C. Kiribati (British Phoenix Is.)', 'OC', false],
  32: ['Ceuta & Melilla', 'AF', false],
  33: ['Chagos Is.', 'AF', false],
  34: ['Chatham Is.', 'OC', false],
  35: ['Christmas I.', 'OC', false],
  36: ['Clipperton I.', 'NA', false],
  37: ['Cocos I.', 'NA', false],
  38: ['Cocos (Keeling) Is.', 'OC', false],
  39: ['Comoros', 'AF', true],
  40: ['Crete', 'EU', false],
  41: ['Crozet I.', 'AF', false],
  42: ['Damao, Diu', 'AS', true],
  43: ['Desecheo I.', 'NA', false],
  44: ['Desroches', 'AF', true],
  45: ['Dodecanese', 'EU', false],
  46: ['East Malaysia', 'OC', false],
  47: ['Easter I.', 'SA', false],
  48: ['E. Kiribati (Line Is.)', 'OC', false],
  49: ['Equatorial Guinea', 'AF', false],
  50: ['Mexico', 'NA', false],
  51: ['Eritrea', 'AF', false],
  52: ['Estonia', 'EU', false],
  53: ['Ethiopia', 'AF', false],
  54: ['European Russia', 'EU', false],
  55: ['Farquhar', 'AF', true],
  56: ['Fernando de Noronha', 'SA', false],
  57: ['French Equatorial Africa', 'AF', true],
  58: ['French Indo-China', 'AS', true],
  59: ['French West Africa', 'AF', true],
  60: ['Bahamas', 'NA', false],
  61: ['Franz Josef Land', 'EU', false],
  62: ['Barbados', 'NA', false],
  63: ['French Guiana', 'SA', false],
  64: ['Bermuda', 'NA', false],
  65: ['British Virgin Is.', 'NA', false],
  66: ['Belize', 'NA', false],
  67: ['French India', 'AS', true],
  68: ['Kuwait/Saudi Arabia Neutral Zone', 'AS', true],
  69: ['Cayman Is.', 'NA', false],
  70: ['Cuba', 'NA', false],
  71: ['Galapagos Is.', 'SA', false],
  72: ['Dominican Republic', 'NA', false],
  74: ['El Salvador', 'NA', false],
  75: ['Georgia', 'AS', false],
  76: ['Guatemala', 'NA', false],
  77: ['Grenada', 'NA', false],
  78: ['Haiti', 'NA', false],
  79: ['Guadeloupe', 'NA', false],
  80: ['Honduras', 'NA', false],
  81: ['Germany', 'EU', true],
  82: ['Jamaica', 'NA', false],
  84: ['Martinique', 'NA', false],
  85: ['Bonaire, Curacao', 'SA', true],
  86: ['Nicaragua', 'NA', false],
  88: ['Panama', 'NA', false],
  89: ['Turks & Caicos Is.', 'NA', false],
  90: ['Trinidad & Tobago', 'SA', false],
  91: ['Aruba', 'SA', false],
  93: ['Geyser Reef', 'AF', true],
  94: ['Antigua & Barbuda', 'NA', false],
  95: ['Dominica', 'NA', false],
  96: ['Montserrat', 'NA', false],
  97: ['St. Lucia', 'NA', false],
  98: ['St. Vincent', 'NA', false],
  99: ['Glorioso Is.', 'AF', false],
  100: ['Argentina', 'SA', false],
  101: ['Goa', 'AS', true],
  102: ['Gold Coast, Togoland', 'AF', true],
  103: ['Guam', 'OC', false],
  104: ['Bolivia', 'SA', false],
  105: ['Guantanamo Bay', 'NA', false],
  106: ['Guernsey', 'EU', false],
  107: ['Guinea', 'AF', false],
  108: ['Brazil', 'SA', false],
  109: ['Guinea-Bissau', 'AF', false],
  110: ['Hawaii', 'OC', false],
  111: ['Heard I.', 'AF', false],
  112: ['Chile', 'SA', false],
  113: ['Ifni', 'AF', true],
  114: ['Isle of Man', 'EU', false],
  115: ['Italian Somaliland', 'AF', true],
  116: ['Colombia', 'SA', false],
  117: ['ITU HQ', 'EU', false],
  118: ['Jan Mayen', 'EU', false],
  119: ['Java', 'OC', true],
  120: ['Ecuador', 'SA', false],
  122: ['Jersey', 'EU', false],
  123: ['Johnston I.', 'OC', false],
  124: ['Juan de Nova, Europa', 'AF', false],
  125: ['Juan Fernandez Is.', 'SA', false],
  126: ['Kaliningrad', 'EU', false],
  127: ['Kamaran Is.', 'AS', true],
  128: ['Karelo-Finnish Republic', 'EU', true],
  129: ['Guyana', 'SA', false],
  130: ['Kazakhstan', 'AS', false],
  131: ['Kerguelen Is.', 'AF', false],
  132: ['Paraguay', 'SA', false],
  133: ['Kermadec Is.', 'OC', false],
  134: ['Kingman Reef', 'OC', true],
  135: ['Kyrgyzstan', 'AS', false],
  136: ['Peru', 'SA', false],
  137: ['Republic of Korea', 'AS', false],
  138: ['Kure I.', 'OC', false],
  139: ['Kuria Muria I.', 'AS', true],
  140: ['Suriname', 'SA', false],
  141: ['Falkland Is.', 'SA', false],
  142: ['Lakshadweep Is.', 'AS', false],
  143: ['Laos', 'AS', false],
  144: ['Uruguay', 'SA', false],
  145: ['Latvia', 'EU', false],
  146: ['Lithuania', 'EU', false],
  147: ['Lord Howe I.', 'OC', false],
  148: ['Venezuela', 'SA', false],
  149: ['Azores', 'EU', false],
  150: ['Australia', 'OC', false],
  151: ['Malyj Vysotskij I.', 'EU', true],
  152: ['Macao', 'AS', false],
  153: ['Macquarie I.', 'OC', false],
  154: ['Yemen Arab Republic', 'AS', true],
  155: ['Malaya', 'AS', true],
  157: ['Nauru', 'OC', false],
  158: ['Vanuatu', 'OC', false],
  159: ['Maldives', 'AS', false],
  160: ['Tonga', 'OC', false],
  161: ['Malpelo I.', 'SA', false],
  162: ['New Caledonia', 'OC', false],
  163: ['Papua New Guinea', 'OC', false],
  164: ['Manchuria', 'AS', true],
  165: ['Mauritius', 'AF', false],
  166: ['Mariana Is.', 'OC', false],
  167: ['Market Reef', 'EU', false],
  168: ['Marshall Is.', 'OC', false],
  169: ['Mayotte', 'AF', false],
  170: ['New Zealand', 'OC', false],
  171: ['Mellish Reef', 'OC', false],
  172: ['Pitcairn I.', 'OC', false],
  173: ['Micronesia', 'OC', false],
  174: ['Midway I.', 'OC', false],
  175: ['French Polynesia', 'OC', false],
  176: ['Fiji', 'OC', false],
  177: ['Minami Torishima', 'OC', false],
  178: ['Minerva Reef', 'OC', true],
  179: ['Moldova', 'EU', false],
  180: ['Mount Athos', 'EU', false],
  181: ['Mozambique', 'AF', false],
  182: ['Navassa I.', 'NA', false],
  183: ['Netherlands Borneo', 'OC', true],
  184: ['Netherlands New Guinea', 'OC', true],
  185: ['Solomon Is.', 'OC', false],
  186: ['Newfoundland, Labrador', 'NA', true],
  187: ['Niger', 'AF', false],
  188: ['Niue', 'OC', false],
  189: ['Norfolk I.', 'OC', false],
  190: ['Samoa', 'OC', false],
  191: ['North Cook Is.', 'OC', false],
  192: ['Ogasawara', 'AS', false],
  193: ['Okinawa (Ryukyu Is.)', 'AS', true],
  194: ['Okino Tori-Shima', 'AS', true],
  195: ['Annobon I.', 'AF', false],
  196: ['Palestine', 'AS', true],
  197: ['Palmyra & Jarvis Is.', 'OC', false],
  198: ['Papua Territory', 'OC', true],
  199: ['Peter 1 I.', 'AN', false],
  200: ['Portuguese Timor', 'OC', true],
  201: ['Prince Edward & Marion Is.', 'AF', false],
  202: ['Puerto Rico', 'NA', false],
  203: ['Andorra', 'EU', false],
  204: ['Revillagigedo', 'NA', false],
  205: ['Ascension I.', 'AF', false],
  206: ['Austria', 'EU', false],
  207: ['Rodrigues I.', 'AF', false],
  208: ['Ruanda-Urundi', 'AF', true],
  209: ['Belgium', 'EU', false],
  210: ['Saar', 'EU', true],
  211: ['Sable I.', 'NA', false],
  212: ['Bulgaria', 'EU', false],
  213: ['Saint Martin', 'NA', false],
  214: ['Corsica', 'EU', false],
  215: ['Cyprus', 'AS', false],
  216: ['San Andres & Providencia', 'NA', false],
  217: ['San Felix & San Ambrosio', 'SA', false],
  218: ['Czechoslovakia', 'EU', true],
  219: ['Sao Tome & Principe', 'AF', false],
  220: ['Sarawak', 'OC', true],
  221: ['Denmark', 'EU', false],
  222: ['Faroe Is.', 'EU', false],
  223: ['England', 'EU', false],
  224: ['Finland', 'EU', false],
  225: ['Sardinia', 'EU', false],
  226: ['Saudi Arabia/Iraq Neutral Zone', 'AS', true],
  227: ['France', 'EU', false],
  228: ['Serrana Bank & Roncador Cay', 'NA', true],
  229: ['German Democratic Republic', 'EU', true],
  230: ['Fed. Rep. of Germany', 'EU', false],
  231: ['Sikkim', 'AS', true],
  232: ['Somalia', 'AF', false],
  233: ['Gibraltar', 'EU', false],
  234: ['South Cook Is.', 'OC', false],
  235: ['South Georgia I.', 'SA', false],
  236: ['Greece', 'EU', false],
  237: ['Greenland', 'NA', false],
  238: ['South Orkney Is.', 'SA', false],
  239: ['Hungary', 'EU', false],
  240: ['South Sandwich Is.', 'SA', false],
  241: ['South Shetland Is.', 'AN', false],
  242: ['Iceland', 'EU', false],
  243: ["People's Dem. Rep. of Yemen", 'AS', true],
  244: ['Southern Sudan', 'AF', true],
  245: ['Ireland', 'EU', false],
  246: ['Sov. Mil. Order of Malta', 'EU', false],
  247: ['Spratly Is.', 'AS', false],
  248: ['Italy', 'EU', false],
  249: ['St. Kitts & Nevis', 'NA', false],
  250: ['St. Helena', 'AF', false],
  251: ['Liechtenstein', 'EU', false],
  252: ['St. Paul I.', 'NA', false],
  253: ['St. Peter & St. Paul Rocks', 'SA', false],
  254: ['Luxembourg', 'EU', false],
  255: ['St. Maarten, Saba, St. Eustatius', 'NA', true],
  256: ['Madeira Is.', 'AF', false],
  257: ['Malta', 'EU', false],
  258: ['Sumatra', 'OC', true],
  259: ['Svalbard', 'EU', false],
  260: ['Monaco', 'EU', false],
  261: ['Swan Is.', 'NA', true],
  262: ['Tajikistan', 'AS', false],
  263: ['Netherlands', 'EU', false],
  264: ['Tangier', 'AF', true],
  265: ['Northern Ireland', 'EU', false],
  266: ['Norway', 'EU', false],
  267: ['Territory of New Guinea', 'OC', true],
  268: ['Tibet', 'AS', true],
  269: ['Poland', 'EU', false],
  270: ['Tokelau Is.', 'OC', false],
  271: ['Trieste', 'EU', true],
  272: ['Portugal', 'EU', false],
  273: ['Trindade & Martim Vaz Is.', 'SA', false],
  274: ['Tristan da Cunha & Gough I.', 'AF', false],
  275: ['Romania', 'EU', false],
  276: ['Tromelin I.', 'AF', false],
  277: ['St. Pierre & Miquelon', 'NA', false],
  278: ['San Marino', 'EU', false],
  279: ['Scotland', 'EU', false],
  280: ['Turkmenistan', 'AS', false],
  281: ['Spain', 'EU', false],
  282: ['Tuvalu', 'OC', false],
  283: ['UK Sov. Base Areas on Cyprus', 'AS', false],
  284: ['Sweden', 'EU', false],
  285: ['Virgin Is.', 'NA', false],
  286: ['Uganda', 'AF', false],
  287: ['Switzerland', 'EU', false],
  288: ['Ukraine', 'EU', false],
  289: ['United Nations HQ', 'NA', false],
  291: ['United States of America', 'NA', false],
  292: ['Uzbekistan', 'AS', false],
  293: ['Viet Nam', 'AS', false],
  294: ['Wales', 'EU', false],
  295: ['Vatican', 'EU', false],
  296: ['Serbia', 'EU', false],
  297: ['Wake I.', 'OC', false],
  298: ['Wallis & Futuna Is.', 'OC', false],
  299: ['West Malaysia', 'AS', false],
  301: ['W. Kiribati (Gilbert Is.)', 'OC', false],
  302: ['Western Sahara', 'AF', false],
  303: ['Willis I.', 'OC', false],
  304: ['Bahrain', 'AS', false],
  305: ['Bangladesh', 'AS', false],
  306: ['Bhutan', 'AS', false],
  307: ['Zanzibar', 'AF', true],
  308: ['Costa Rica', 'NA', false],
  309: ['Myanmar', 'AS', false],
  312: ['Cambodia', 'AS', false],
  315: ['Sri Lanka', 'AS', false],
  318: ['China', 'AS', false],
  321: ['Hong Kong', 'AS', false],
  324: ['India', 'AS', false],
  327: ['Indonesia', 'OC', false],
  330: ['Iran', 'AS', false],
  333: ['Iraq', 'AS', false],
  336: ['Israel', 'AS', false],
  339: ['Japan', 'AS', false],
  342: ['Jordan', 'AS', false],
  344: ["Dem. People's Rep. of Korea", 'AS', false],
  345: ['Brunei Darussalam', 'OC', false],
  348: ['Kuwait', 'AS', false],
  354: ['Lebanon', 'AS', false],
  363: ['Mongolia', 'AS', false],
  369: ['Nepal', 'AS', false],
  370: ['Oman', 'AS', false],
  372: ['Pakistan', 'AS', false],
  375: ['Philippines', 'OC', false],
  376: ['Qatar', 'AS', false],
  378: ['Saudi Arabia', 'AS', false],
  379: ['Seychelles', 'AF', false],
  381: ['Singapore', 'AS', false],
  382: ['Djibouti', 'AF', false],
  384: ['Syria', 'AS', false],
  386: ['Taiwan', 'AS', false],
  387: ['Thailand', 'AS', false],
  390: ['Turkey', 'EU', false],
  391: ['United Arab Emirates', 'AS', false],
  400: ['Algeria', 'AF', false],
  401: ['Angola', 'AF', false],
  402: ['Botswana', 'AF', false],
  404: ['Burundi', 'AF', false],
  406: ['Cameroon', 'AF', false],
  408: ['Central Africa', 'AF', false],
  409: ['Cape Verde', 'AF', false],
  410: ['Chad', 'AF', false],
  411: ['Comoros', 'AF', false],
  412: ['Republic of the Congo', 'AF', false],
  414: ['Dem. Rep. of the Congo', 'AF', false],
  416: ['Benin', 'AF', false],
  420: ['Gabon', 'AF', false],
  422: ['The Gambia', 'AF', false],
  424: ['Ghana', 'AF', false],
  428: ["Cote d'Ivoire", 'AF', false],
  430: ['Kenya', 'AF', false],
  432: ['Lesotho', 'AF', false],
  434: ['Liberia', 'AF', false],
  436: ['Libya', 'AF', false],
  438: ['Madagascar', 'AF', false],
  440: ['Malawi', 'AF', false],
  442: ['Mali', 'AF', false],
  444: ['Mauritania', 'AF', false],
  446: ['Morocco', 'AF', false],
  450: ['Nigeria', 'AF', false],
  452: ['Zimbabwe', 'AF', false],
  453: ['Reunion I.', 'AF', false],
  454: ['Rwanda', 'AF', false],
  456: ['Senegal', 'AF', false],
  458: ['Sierra Leone', 'AF', false],
  460: ['Rotuma I.', 'OC', false],
  462: ['Republic of South Africa', 'AF', false],
  464: ['Namibia', 'AF', false],
  466: ['Sudan', 'AF', false],
  468: ['Kingdom of Eswatini', 'AF', false],
  470: ['Tanzania', 'AF', false],
  474: ['Tunisia', 'AF', false],
  478: ['Egypt', 'AF', false],
  480: ['Burkina Faso', 'AF', false],
  482: ['Zambia', 'AF', false],
  483: ['Togo', 'AF', false],
  488: ['Walvis Bay', 'AF', true],
  489: ['Conway Reef', 'OC', false],
  490: ['Banaba I. (Ocean I.)', 'OC', false],
  492: ['Yemen', 'AS', false],
  493: ['Penguin Is.', 'AF', true],
  497: ['Croatia', 'EU', false],
  499: ['Slovenia', 'EU', false],
  501: ['Bosnia-Herzegovina', 'EU', false],
  502: ['North Macedonia', 'EU', false],
  503: ['Czech Republic', 'EU', false],
  504: ['Slovak Republic', 'EU', false],
  505: ['Pratas I.', 'AS', false],
  506: ['Scarborough Reef', 'AS', false],
  507: ['Temotu Province', 'OC', false],
  508: ['Austral I.', 'OC', false],
  509: ['Marquesas Is.', 'OC', false],
  510: ['Palestine', 'AS', false],
  511: ['Timor-Leste', 'OC', false],
  512: ['Chesterfield Is.', 'OC', false],
  513: ['Ducie I.', 'OC', false],
  514: ['Montenegro', 'EU', false],
  515: ['Swains I.', 'OC', false],
  516: ['Saint Barthelemy', 'NA', false],
  517: ['Curacao', 'SA', false],
  518: ['Sint Maarten', 'NA', false],
  519: ['Saba & St. Eustatius', 'NA', false],
  520: ['Bonaire', 'SA', false],
  521: ['South Sudan', 'AF', false],
  522: ['Republic of Kosovo', 'EU', false],
}

/**
 * Look up DXCC entity by code
 * @param {string|number} code - DXCC entity code
 * @returns {{ name: string, cont: string, deleted: boolean } | null}
 */
export function lookupDXCC(code) {
  const entry = DXCC_ENTITIES[Number(code)]
  if (!entry) return null
  return { name: entry[0], cont: entry[1], deleted: entry[2] }
}

export default DXCC_ENTITIES
